import { ReviewFinding, offersFix, summariseReview } from './code-review';
import { OutboundAction } from './task-sources';

// ─── Posting a review to a pull request (Phase 9, M48 · P9-6) ──────────────
//
// The Reviewer produces findings (M47). This turns them into a GitHub pull-request
// review — and does so through M67/M68's per-action confirmation, which is the entire
// content of the acceptance clause: **never ambient.**
//
// ── What "never ambient" costs, and why it is worth it ──────────────────────
// The natural design is a setting: "post reviews automatically when a PR is opened."
// It would be one boolean and it is exactly what E8 forbids, because the tenth review
// posted under the user's name is authorised by a checkbox they ticked three weeks ago on
// a different repository. `decideOutbound`'s context type has no field for a remembered
// answer, so this module cannot express a standing grant even by mistake — the only way
// to add one is to change that type, which is a change a reviewer sees.
//
// ── The body is built here, and it is not the artifact ─────────────────────
// A PR review is read by people who did not run the reviewer, in a thread that outlives
// the branch. So it says what produced it, and it drops the fix suggestions: a code
// suggestion posted to a colleague's PR under your name, generated by a model you ran
// locally, is a different social act from one you wrote. The findings are the useful
// part; the fixes belong in the editor where the person who ran the review can apply and
// inspect them.

/** Everything needed to address a review to a PR. */
export interface PrTarget {
    owner: string;
    repo: string;
    /** Pull request number. */
    number: number;
    /** For the confirmation prompt, so the user recognises what they are posting to. */
    title?: string;
}

/**
 * A GitHub review payload.
 *
 * `event: 'COMMENT'` always, never `REQUEST_CHANGES` or `APPROVE`. Both of those are
 * *decisions about someone's work* with process consequences — a requested change blocks
 * a merge, an approval unblocks one — and neither is a call a locally-run model gets to
 * make under the user's identity. A comment says the same things and asserts nothing.
 */
export interface GhReviewPayload {
    body: string;
    event: 'COMMENT';
    comments: { path: string; line: number; body: string }[];
}

/**
 * Turn findings into a review payload.
 *
 * Findings with a line become inline comments; the rest go in the body. That split is not
 * cosmetic: an inline comment on GitHub is anchored to the diff and is what a reviewer
 * actually reads, while a body-only review of nine findings is a wall nobody maps back
 * to the code.
 */
export function buildReviewPayload(
    findings: ReviewFinding[],
    options: { model?: string; maxInline?: number } = {},
): GhReviewPayload {
    const summary = summariseReview(findings);
    const maxInline = options.maxInline ?? 20;

    const inline = findings.filter(f => f.line > 0).slice(0, maxInline);
    const rest = findings.filter(f => !inline.includes(f));

    const header = findings.length
        ? [
            `**Automated review** — ${summary.total} finding(s): `
            + `${summary.high} high, ${summary.medium} medium, ${summary.low} low.`,
            '',
            `Produced by Black IDE${options.model ? ` using ${options.model}` : ''} and posted by a human who read it. `
            + 'Each finding names a concrete failure; treat them as a second pair of eyes, not a verdict.',
        ]
        : [
            '**Automated review** — no findings.',
            '',
            'The reviewer read the diff and could not ground a defect in a concrete failure. '
            + 'That is one read of it, not a guarantee it is correct.',
        ];

    const body = [...header];
    if (rest.length) {
        body.push('', '### Findings not anchored to a line', '');
        for (const finding of rest) body.push(`- ${severityMark(finding.severity)} **${finding.summary}** (\`${finding.file}\`) — ${finding.failureScenario}`);
    }
    if (inline.length < findings.filter(f => f.line > 0).length) {
        // Said out loud rather than silently truncated: a review that shows twenty of
        // thirty findings and does not say so reads as a complete review.
        body.push('', `_${findings.filter(f => f.line > 0).length - inline.length} further finding(s) were not posted — the review was capped at ${maxInline} inline comments._`);
    }

    return {
        body: body.join('\n'),
        event: 'COMMENT',
        comments: inline.map(finding => ({
            path: finding.file,
            line: finding.line,
            body: [
                `${severityMark(finding.severity)} **${finding.summary}**`,
                '',
                `**Fails when:** ${finding.failureScenario}`,
                '',
                `_${finding.category} · confidence ${Math.round(finding.confidence * 100)}%_`,
                // Deliberately no `suggestion` block, even where one exists. See the
                // module header: a generated code suggestion on a colleague's PR under
                // your name is a different act from one you wrote.
                offersFix(finding) ? '_A suggested fix is available in the editor._' : '',
            ].filter(Boolean).join('\n'),
        })),
    };
}

function severityMark(severity: ReviewFinding['severity']): string {
    return severity === 'high' ? '🔴' : severity === 'medium' ? '🟡' : '⚪';
}

/**
 * The outbound action a user confirms.
 *
 * `body` carries the **whole payload**, rendered as it will appear, because
 * `buildConfirmation` shows it verbatim and a confirmation the user has not read is not
 * one. Summarising it here would defeat the gate at the one point the gate exists.
 */
export function reviewOutboundAction(target: PrTarget, payload: GhReviewPayload): OutboundAction {
    const inline = payload.comments.length
        ? ['', '--- inline comments ---', ...payload.comments.map(c => `${c.path}:${c.line}\n${c.body}`)]
        : [];
    return {
        kind: 'comment',
        destination: `${target.owner}/${target.repo}#${target.number}${target.title ? ` (${target.title})` : ''}`,
        body: [payload.body, ...inline].join('\n'),
    };
}

/**
 * The `gh` argv that posts it.
 *
 * An argument array with the payload on **stdin**, not an interpolated shell string. The
 * body contains a model's prose about a diff — backticks, quotes, `$(…)` if a finding
 * quotes shell code — and every one of those is a metacharacter in a shell string. This
 * is the one call in the codebase where untrusted text meets a command line, so it never
 * becomes a command line.
 */
export function buildGhReviewCommand(target: PrTarget): { argv: string[]; stdin: (payload: GhReviewPayload) => string } {
    return {
        argv: [
            'api',
            '--method', 'POST',
            `repos/${target.owner}/${target.repo}/pulls/${target.number}/reviews`,
            '--input', '-',
        ],
        stdin: payload => JSON.stringify(payload),
    };
}

/**
 * Parse `gh pr view --json` output into a target.
 *
 * Returns `undefined` rather than a partial target: a review posted to the wrong PR
 * number is the failure this whole feature must not have, and half a target is how you
 * get one.
 */
export function parsePrTarget(json: string, nameWithOwner?: string): PrTarget | undefined {
    let parsed: any;
    try { parsed = JSON.parse(json); } catch { return undefined; }

    const number = Number(parsed?.number);
    if (!Number.isInteger(number) || number <= 0) return undefined;

    const slug = String(parsed?.headRepository?.nameWithOwner || nameWithOwner || '').trim();
    const [owner, repo] = slug.split('/');
    if (!owner || !repo) return undefined;

    return { owner, repo, number, title: parsed?.title ? String(parsed.title) : undefined };
}
